### ISSUE TITLE
Including Cell border stain information

### ISSUE THREAD

**Issue by pakiessling** [SydneyBioX/BIDCell#1]
Hi, thank you for the tool and congratulations on the preprint.

I am quite excited to try it out.

In your manuscript you mention: "BIDCell can be further adapted (e.g., via its cell-calling loss) to incorporate cell membrane markers ".

I work with Merfish data where the membrane stain works quite nicely.
Could you give me some pointers on how to best leverage that?

**Comment by xhelenfu** [comment]
Hi, thanks for your question. We are currently in the process of adding more options to BIDCell, including the use of membrane stains. We are benchmarking different approaches to use membrane stains and will be updating the code with this new option.

**Comment by pakiessling** [comment]
@xhelenfu Exciting to hear, I will watch your repor with interest :)
