### ISSUE TITLE
Using GPU v CPU

### ISSUE THREAD

**Issue by johnyaku** [SydneyBioX/BIDCell#2]
Just trying to verify my understanding is correct. Can you please confirm the following?

1. By default, BIDCell will try to a use a GPU if one is available
2. This can be turned off by specifying `nuclei.use_cpu` in the config

**Comment by johnyaku** [comment]
Follow up question on the same theme ...

Which of the following steps in the pipeline actually utilize the GPU? 
- segment_nuclei
- generate_expression_maps
- generate_patches
- make_cell_gene_mat
- preannotate
- train
- predict

**Comment by xhelenfu** [comment]
1. By default, BIDCell will try to a use a GPU if one is available
        Yes, the code will try to use a GPU by default, but will use CPU if a GPU is not available 
2. This can be turned off by specifying nuclei.use_cpu in the config
        This will only apply to the nuclei segmentation step, not the cell segmentation step 

These steps use the GPU:
- segment_nuclei
- train
- predict

**Comment by johnyaku** [comment]
Thanks @xhelenfu!

More questions coming, I suspect!
