### ISSUE TITLE
Request for open all code especially for the reference data part

### ISSUE THREAD

**Issue by aqlkzf** [SydneyBioX/BIDCell#5]
Can you please share the code for processing reference data to obtain sc_references/sc_breast.csv, sc_breast_markers_pos.csv, and sc_breast_markers_neg.csv?

**Comment by aqlkzf** [comment]
Any response?

**Comment by Ceyhun-Alar** [comment]
I am also wondering if you guys can share your reference data processing? How do we obtain the sc_breast.csv, sc_breast_markers_pos.csv, and sc_breast_markers_neg.csv?

**Comment by VPetukhov** [comment]
I have the same question. Could not find the code. The docs said that it should be cell type average, but what is the "atlas" column? And why some cell types have multiple entries?
