### ISSUE TITLE
Unable to generate  transcripts.csv.gz and morphology_mip.ome.tif files.

### ISSUE THREAD

**Issue by PhilCollinsChidi** [SydneyBioX/BIDCell#8]
I have try to run this set of codes several times, but i am unable to get **transcripts.csv.gz and morphology_mip.ome.tif files.**

from bidcell import BIDCellModel
BIDCellModel.get_example_data()
model = BIDCellModel("params_small_example.yaml")
model.run_pipeline()

Can someone help explain to me what i am doing wrongly.

**Comment by xhelenfu** [comment]
Hi, these files may be downloaded from public sources or be your own data. For example, the full dataset (Xenium Output Bundle In Situ Replicate 1) may be downloaded from https://www.10xgenomics.com/products/xenium-in-situ/preview-dataset-human-breast. The breast cancer reference data are provided with this package under `data/sc_references`, or `./example_data/sc_references` if you have run `example_small.py`. Please ensure the correct paths are provided for the parameters under `files` in `xenium_example_config.yaml`, in particular, the paths for the transcripts (`transcripts.csv.gz`) and DAPI (`morphology_mip.ome.tif`) files.

**Comment by PhilCollinsChidi** [comment]
Hi there,

Thank you for the response and clarification.

Kind regards,
Phil
